ualibweb/mod-data-export-worker

.gitmodules, pom.xml, src/main/java/org/folio/dew/batch/bursarfeesfines/AccountItemProcessor.java, src/main/java/org/folio/dew/batch/bursarfeesfines/FeefineActionItemProcessor.java, src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarExportService.java, src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarFeesFinesUtils.java, src/main/java/org/folio/dew/batch/bursarfeesfines/service/impl/BursarExportServiceImpl.java, src/main/java/org/folio/dew/domain/dto/bursarfeesfines/BursarFeeFinesDto.java, src/main/java/org/folio/dew/service/JobCommandsReceiverService.java, src/main/resources/swagger.api/bursar-export.yaml, src/test/java/org/folio/dew/BursarFeesFinesTest.java
=> Add bursar schema

src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarTokenFormatter.java
=> added support for date data token - #34

src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarTokenFormatter.java
=> caught exception on unknown timezone - closes #34

src/main/java/org/folio/dew/batch/bursarfeesfines/BursarExportJobConfig.java, src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarTokenFormatter.java, src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarWriter.java
=> Add constant header/footer support

src/main/java/org/folio/dew/batch/bursarfeesfines/AccountReader.java, src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarTokenFormatter.java
=> add support for fee amounts data token - #32

src/main/java/org/folio/dew/batch/bursarfeesfines/AccountReader.java, src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarTokenFormatter.java
=> Add support for fee metadata data tokens - #35

src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarTokenFormatter.java
=> add support for user data token - closes #36

src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarFilterEvaluator.java
Note: Correct branch name should be `faruq-issue-13`
While it's helpful for reviewers to …
=> refine fetching to allow filtering on: fine age - closes #13

src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarFilterEvaluator.java
=> Refine fetching to allow filtering on: fee type - closes #16

src/main/java/org/folio/dew/batch/bursarfeesfines/AccountFormatter.java, src/main/java/org/folio/dew/batch/bursarfeesfines/AccountReader.java, src/main/java/org/folio/dew/batch/bursarfeesfines/BursarExportJobConfig.java, src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarTokenFormatter.java, src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarWriter.java
=> Add support for header/footer aggregate token 

src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarTokenFormatter.java
=> Add support for constant conditional token and clean up imports

src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarFilterEvaluator.java
=> Refine fetching to allow filtering on: service point

src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarTokenFormatter.java
=> add supoort for item metadata data token - closes #33

src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarFilterEvaluator.java
=> allow filtering on fine amount - closes #14

src/main/java/org/folio/dew/batch/bursarfeesfines/AccountFilterer.java, src/main/java/org/folio/dew/batch/bursarfeesfines/BursarExportJobConfig.java, src/main/java/org/folio/dew/batch/bursarfeesfines/TransferFeesFinesTasklet.java
=> Get filtered accounts in TransferFeesFinesTasklet - closes #68

src/main/java/org/folio/dew/batch/bursarfeesfines/AggregatedAccountFilterer.java, src/main/java/org/folio/dew/batch/bursarfeesfines/AggregatedAccountFormatter.java, src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarFilterAggregateEvaluator.java, src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarTokenFormatter.java, src/main/java/org/folio/dew/domain/dto/bursarfeesfines/AggregatedAccountsByUser.java
@ncovercash  The only user related filter was by PatronGroup so I only added AggregatedAccounts filter by Patron Group. Lmk if there is anything I should change.
=> Add support for formatting aggregated accounts by users

src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarTokenFormatter.java
=> Add support for new data token - Conditional - #81

src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarFilterEvaluator.java, src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarTokenFormatter.java
To implement #84 
While it's helpful for reviewers to help identify potential problems, …
=> Add support for new filter - #84

src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarFilterEvaluator.java, src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarTokenFormatter.java
=> Extend user data token: include external system ID

pom.xml, src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarFilterEvaluator.java, src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarTokenFormatter.java, src/test/java/org/folio/dew/batch/bursarfeesfines/service/BursarFilterEvaluatorTest.java, src/test/java/org/folio/dew/helpers/bursarfeesfines/InvalidBursarExportFilter.java
=> Create unit tests for BursarFilterEvaluator - #101

src/test/java/org/folio/dew/batch/bursarfeesfines/service/BursarExportUtilsTest.java
=> Unit test for BursarExportUtils

src/main/java/org/folio/dew/batch/bursarfeesfines/AggregatedAccountReader.java, src/test/java/org/folio/dew/batch/bursarfeesfines/service/AggregatedAccountReaderTest.java
This is my attempt at refactoring at writing unit test for `AggregatedAccountReader::initStep()`.
=> Modify and write unit test for AggregatedAccountReader 

src/test/java/org/folio/dew/BursarFeesFinesTest.java, src/test/resources/mappings/feesfines.json
=> Create an integration test for: no fees/fines whatsoever - closes #105

src/main/java/org/folio/dew/batch/bursarfeesfines/service/impl/BursarExportServiceImpl.java, src/test/java/org/folio/dew/batch/bursarfeesfines/service/impl/BursarExportServiceImplTest.java
=> Create test for BursarExportService

src/main/java/org/folio/dew/batch/bursarfeesfines/service/BursarFilterEvaluator.java, src/test/java/org/folio/dew/batch/bursarfeesfines/service/BursarFilterEvaluatorTest.java
=> Add conditions to filter age 
